osx_image: xcode8.3

dist: trusty
sudo: true

language: node_js
node_js: "lts/*"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y rpm; fi
  - npm update @suen/music-api
  
script:
  - npm run build-file
  - npm run build:normal
  - if [ $TRAVIS_OS_NAME = osx ]; then npm run build:win; fi

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    - releases/*
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email: false